# 🧑‍💻 NumPy Complete Guided Project
**Instructor / Student Colab Notebook** – covers *all* key concepts from `Numpy‑1` to `Numpy‑5`.

*Generated: 08 Aug 2025*


**Table of Contents**

1. [Setup](#setup)  
2. [Array Creation & Dtypes](#creation)  
3. [Array Attributes & Inspection](#attributes)  
4. [Indexing, Slicing, Fancy Indexing](#indexing)  
5. [Reshaping, Transpose & Copies vs Views](#reshape)  
6. [Joining, Splitting, Set & Sorting Ops](#join)  
7. [Arithmetic Ops, Universal Functions](#arithmetic)  
8. [Broadcasting (Rules + Examples)](#broadcast)  
9. [Statistics & Aggregations](#stats)  
10. [Random Numbers & Reproducibility](#random)  
11. [Structured / Recarrays](#structured)  
12. [Linear Algebra Essentials](#linalg)  
13. [File I/O (`npy`, `npz`, `txt`)](#io)  
14. [Datetime64 & Timedelta64](#datetime)  
15. [Masked Arrays & NaNs](#mask)  
16. [Mini‑Project — Fitness Data Analysis](#project)  
17. [Conclusion & Next Steps](#conclusion)  


## <a name='setup'></a>1️⃣ Setup

In [32]:
import numpy as np, math, os, pathlib, types, textwrap, random
print('NumPy version:', np.__version__)

NumPy version: 2.0.2


## <a name='creation'></a>2️⃣ Array Creation & Dtypes

Key functions: `np.array`, `np.arange`, `np.linspace`, `zeros`, `ones`, `full`, `eye`, `identity`, `diag`, `empty`

In [33]:
# EXAMPLE
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.linspace(0, 1, 6)
arr3 = np.full((2,3), 7.5)
print(arr1, arr2, arr3, sep="\n")
print("dtypes:", arr1.dtype, arr2.dtype)


[1 2 3]
[0.  0.2 0.4 0.6 0.8 1. ]
[[7.5 7.5 7.5]
 [7.5 7.5 7.5]]
dtypes: int32 float64


In [34]:
# 🖊️ TODO: create a 10×10 chessboard pattern using zeros & ones
arr = np.zeros((10,10),dtype=int)

# for i in range(10):
#   for j in range(10):
#     if (i+j)%2 == 1:
#       arr[i][j]=1

#using slicing
arr[1::2,::2]=1
arr[::2,1::2]=1
print(arr)


[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


## <a name='attributes'></a>3️⃣ Array Attributes & Inspection

`shape`, `ndim`, `size`, `dtype`, `itemsize`, `nbytes`

In [35]:
M = np.arange(12).reshape(3,4)
print('shape', M.shape, 'ndim', M.ndim, 'size', M.size, 'itemsize', M.itemsize, 'total bytes', M.nbytes)


shape (3, 4) ndim 2 size 12 itemsize 8 total bytes 96


In [36]:
# 🖊️ TODO: check memory footprint of a 1000×1000 float64 array
arr= np.zeros((1000,1000),dtype=np.float64)
print('Shape:',arr.shape,'Dimensions:',arr.ndim,'Size:',arr.size,'Bytes:',arr.nbytes)

Shape: (1000, 1000) Dimensions: 2 Size: 1000000 Bytes: 8000000


## <a name='indexing'></a>4️⃣ Indexing, Slicing & Fancy Indexing

In [37]:
a = np.arange(1,26).reshape(5,5)
print(a[:, 0])     # first column
print(a[::2, ::2]) # every 2nd row/col
mask = (a % 3 == 0)
print('multiples of 3:', a[mask])


[ 1  6 11 16 21]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
multiples of 3: [ 3  6  9 12 15 18 21 24]


In [38]:
# 🖊️ TODO: use fancy indexing to swap first and last rows of `a`
a = np.arange(1,26).reshape(5,5)

# a[[0,4],:]=a[[4,0],:]

a1 = a[0, :].copy()
a[0, :] = a[4, :]
a[4, :] = a1

print(a)


[[21 22 23 24 25]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1  2  3  4  5]]


## <a name='reshape'></a>5️⃣ Reshaping, Transpose & Copies vs Views

In [39]:
b = np.arange(8)
B = b.reshape(2,4)
B[0,0] = 99
print('b is modified:', b)
C = b.reshape(2,4).copy()
C[0,0] = -1
print('b unchanged with copy:', b)


b is modified: [99  1  2  3  4  5  6  7]
b unchanged with copy: [99  1  2  3  4  5  6  7]


In [40]:
# 🖊️ TODO: Flatten a 3‑D array into 1‑D using both `ravel` and `flatten`; observe copy vs view.
a = np.arange(1,10).reshape(3, 3)
print(a)
b=a.flatten()
c=a.ravel()
b[0]=0
print('Unchanged a',a)
print(b)
c[0]=0
print('Changed a',a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Unchanged a [[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 2 3 4 5 6 7 8 9]
Changed a [[0 2 3]
 [4 5 6]
 [7 8 9]]
[0 2 3 4 5 6 7 8 9]


## <a name='join'></a>6️⃣ Joining, Splitting, Set & Sorting Ops

In [41]:
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
print('union', np.union1d(x,y))
print('intersect', np.intersect1d(xy,[1,2,10]))
print('sorted descending', np.sort(xy)[::-1])

union [1 2 3 4 5 6]
intersect [1 2]
sorted descending [6 5 4 3 2 1]


In [42]:
# 🖊️ TODO: split `xy` back into two equal halves using `np.array_split`
xy=np.array([1,2,3,4,5,6])
xy=np.array_split(xy,2)
for i in xy:
  print(i)
a=xy[0]
b=xy[1]
print(a,b)

[1 2 3]
[4 5 6]
[1 2 3] [4 5 6]


## <a name='arithmetic'></a>7️⃣ Arithmetic Ops & Universal Functions

In [43]:
v = np.arange(5)
print('exp', np.exp(v))
print('sin', np.sin(v))
print('vectorised addition', v + 10)


exp [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
sin [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
vectorised addition [10 11 12 13 14]


In [44]:
# 🖊️ TODO: given degrees [0,30,45,60,90], compute radians and sin values.
deg=np.array([0,30,45,60,90])
rad=np.deg2rad(deg)
print('Sin values:',np.sin(rad))

#.sin() takes radians not degrees

Sin values: [0.         0.5        0.70710678 0.8660254  1.        ]


## <a name='broadcast'></a>8️⃣ Broadcasting Rules



```
# This is formatted as code
```

Rules: compare dimensions from right → left; stretch size 1 dims; mismatch error.

In [45]:
row = np.arange(5)
col = np.arange(3).reshape(3,1)
matrix = row + col  # broadcast to 3×5
print(matrix)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]]


In [46]:
# 🖊️ TODO: use broadcasting to create a 10×10 multiplication table.
row= np.arange(1,11)
col=np.arange(1,11).reshape(10,1)
mul_table= row*col
print(mul_table)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## <a name='stats'></a>9️⃣ Statistics & Aggregations

In [47]:
data = np.random.default_rng(0).integers(1, 100, size=(5,4))
print('data\n', data)
print('row sums', data.sum(axis=1))
print('col means', data.mean(axis=0))


data
 [[85 64 51 27]
 [31  5  8  2]
 [18 81 65 91]
 [50 61 97 73]
 [63 54 56 93]]
row sums [227  46 255 281 266]
col means [49.4 53.  55.4 57.2]


In [48]:
# 🖊️ TODO: compute `np.percentile` (25th, 50th, 75th) of flattened `data`.
print(np.percentile(data,[25,50,75]))

[30.  58.5 75. ]


## <a name='random'></a>🔟 Random Numbers & Reproducibility

In [49]:
rng = np.random.default_rng(42)
rand_floats = rng.random(5)
rand_ints = rng.integers(low=10, high=50, size=5)
print(rand_floats, rand_ints)
rng2 = np.random.default_rng(42)
assert np.allclose(rand_floats, rng2.random(5))


[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735] [31 49 39 40 38]


In [50]:
# 🖊️ TODO: simulate rolling a fair six‑sided die 100 times; estimate proportion of 6s.
die_rolls= rng.integers(low=1,high=7,size=100)
sixs= list(die_rolls).count(6)
print(sixs/100)

0.12


## <a name='structured'></a>1️⃣1️⃣ Structured / Record Arrays

In [51]:
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                   dtype=[('name','U10'), ('age','i4'), ('weight','f4')])
print(people['name'], people['age'].mean())


['Alice' 'Bob'] 27.5


In [66]:
# 🖊️ TODO: add a new field 'height' to the structured array using `np.lib.recfunctions.append_fields` (hint: pip install?).
people_extended = np.lib.recfunctions.append_fields(people, 'height', [178.4,157], dtypes='f4', usemask=False)
print(people_extended['height'])
print(people_extended)

[178.4 157. ]
[('Alice', 25, 55. , 178.4) ('Bob', 30, 85.5, 157. )]


## <a name='linalg'></a>1️⃣2️⃣ Linear Algebra Essentials

In [53]:
A = np.random.random((3,3))
b = np.random.random(3)
x = np.linalg.solve(A, b)
print('A·x ≈ b?', np.allclose(A.dot(x), b))


A·x ≈ b? True


In [54]:
# 🖊️ TODO: compute eigenvalues of `A` using `np.linalg.eig`.
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [ 1.17772345 -0.1611385  -0.04067407]
Eigenvectors: [[ 0.91858499  0.23154682 -0.03660205]
 [ 0.15460321  0.79908574 -0.92633079]
 [ 0.36372993 -0.55484057  0.37492874]]


## <a name='io'></a>1️⃣3️⃣ File I/O (`npy`, `npz`, `txt`)

In [55]:
np.save('array.npy', A)
loaded = np.load('array.npy')
print('loaded equals A?', np.allclose(loaded, A))
np.savez('multi_arrays.npz', A=A, b=b)


loaded equals A? True


In [56]:
# 🖊️ TODO: Use `np.savetxt` to write `data` (from stats section) to CSV then reload with `np.loadtxt`.
data = np.random.default_rng(0).integers(1, 100, size=(5, 4))
np.savetxt('data.csv', data, delimiter=',', fmt='%d')
loaded_data = np.loadtxt('data.csv', delimiter=',')
print("Loaded correctly?", np.allclose(data, loaded_data))
print("Reloaded data:\n", loaded_data)

Loaded correctly? True
Reloaded data:
 [[85. 64. 51. 27.]
 [31.  5.  8.  2.]
 [18. 81. 65. 91.]
 [50. 61. 97. 73.]
 [63. 54. 56. 93.]]


## <a name='datetime'></a>1️⃣4️⃣ Datetime64 & Timedelta64

In [57]:
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])


['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'] 1 days


In [58]:
# 🖊️ TODO: find how many Mondays appear in `dates` array.
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
weekdays = dates.astype('datetime64[D]').view('int64') % 7
mondays = np.sum(weekdays == 0)
print(f"Number of Mondays: {mondays}")

Number of Mondays: 13


## <a name='mask'></a>1️⃣5️⃣ Masked Arrays & NaNs

In [59]:
arr = np.array([1, 2, np.nan, 4, np.nan])
masked = np.ma.masked_invalid(arr)
print(masked.mean())


2.3333333333333335


In [60]:
# 🖊️ TODO: replace NaNs with column means in a 2‑D array containing NaNs.
arr = np.array([[1., 2., np.nan, 4., np.nan], [5., 6., 7., 8., 9.]])
col_means = np.nanmean(arr, axis=0)
for i in range(arr.shape[1]):
    arr[np.isnan(arr[:, i]), i] = col_means[i]
print(arr)

[[1. 2. 7. 4. 9.]
 [5. 6. 7. 8. 9.]]


## <a name='project'></a>1️⃣6️⃣ Mini‑Project: Fitness Data Analysis

Load `fitness.txt` (tab‑separated) then follow prompts.

In [61]:
from google.colab import files
uploaded = files.upload()

In [62]:
fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)
print('columns:', fitness.dtype.names, 'rows:', len(fitness))


columns: ('date', 'step_count', 'mood', 'calories_burned', 'hours_of_sleep', 'bool_of_active', 'weight_kg') rows: 96


In [65]:
# 🖊️ TODO: Monthly step count, sleep vs mood correlation, weekly summary, etc.
from scipy.stats import pearsonr
from datetime import datetime
fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)

if '#date' in fitness.dtype.names:
    fitness.dtype.names = tuple(['date' if name == '#date' else name for name in fitness.dtype.names])

# Convert to numpy datetime64
date_strs = [datetime.strptime(d, "%d-%m-%Y").strftime("%Y-%m-%d") for d in fitness['date']]
dates = np.array(date_strs, dtype='datetime64[D]')

# step count monthly
print("Monthly Step Counts:")
months = dates.astype('datetime64[M]')
for month in np.unique(months):
    mask = months == month
    total = fitness['step_count'][mask].sum()
    print(f"{month}: {total} steps")

sleep = np.where(fitness['hours_of_sleep'] == 500, 0, fitness['hours_of_sleep'])

# sleep vs mood
print("Sleep vs Mood Correlation:")
mood = fitness['mood']
corr, _ = pearsonr(sleep, mood)
print(f"Pearson correlation: {corr:.2f}")

# weekly average
print("Weekly Averages (Steps, Sleep):")
weeks = dates.astype('datetime64[W]')
for week in np.unique(weeks):
    mask = weeks == week
    avg_steps = fitness['step_count'][mask].mean()
    avg_sleep = sleep[mask].mean()
    print(f"{week}: Avg Steps = {avg_steps:.0f}, Avg Sleep = {avg_sleep:.1f} hrs")

Monthly Step Counts:
2017-10: 79051 steps
2017-11: 103071 steps
2017-12: 89565 steps
2018-01: 10163 steps
Sleep vs Mood Correlation:
Pearson correlation: 0.21
Weekly Averages (Steps, Sleep):
2017-10-05: Avg Steps = 4742, Avg Sleep = 5.5 hrs
2017-10-12: Avg Steps = 2779, Avg Sleep = 6.1 hrs
2017-10-19: Avg Steps = 2789, Avg Sleep = 5.7 hrs
2017-10-26: Avg Steps = 2294, Avg Sleep = 6.1 hrs
2017-11-02: Avg Steps = 3568, Avg Sleep = 3.9 hrs
2017-11-09: Avg Steps = 3954, Avg Sleep = 5.9 hrs
2017-11-16: Avg Steps = 2911, Avg Sleep = 5.4 hrs
2017-11-23: Avg Steps = 3143, Avg Sleep = 6.1 hrs
2017-11-30: Avg Steps = 2913, Avg Sleep = 7.0 hrs
2017-12-07: Avg Steps = 3213, Avg Sleep = 4.1 hrs
2017-12-14: Avg Steps = 3204, Avg Sleep = 4.4 hrs
2017-12-21: Avg Steps = 2743, Avg Sleep = 4.4 hrs
2017-12-28: Avg Steps = 1857, Avg Sleep = 3.6 hrs
2018-01-04: Avg Steps = 970, Avg Sleep = 4.7 hrs


## <a name='conclusion'></a>1️⃣7️⃣ Conclusion & Further Practice
Congrats on covering **all core NumPy topics** from your five lecture notebooks!

*Keep experimenting, read the official docs, and try converting your NumPy pipelines into Pandas or JAX for more fun.*